config/routes.rb
Cprsite::Application.routes.draw do
  resources :privilege_levels

  
  resources :course_types, :user_sessions, :courses, :organizations, :privilege_levels
  
  resources :users do
	member do
		get 'privilege_levels'
		patch 'update_user_privilege_levels'
	end
  end
  resources :account, :controller => "users"
    
  get "welcome/handsonly"
  get "welcome/learn"
  get "welcome/aed"
  get "welcome/info"
  get "welcome/index"

  root to: 'welcome#index'

 end

app/controllers/course_types_controller.rb
class CourseTypesController < ApplicationController
	def new
		@course_type = CourseType.new
	end
	
	def create
		@course_type = CourseType.new(course_type_params)
		 
		if @course_type.save
			redirect_to @course_type
		else
			render 'new'
		end
	end
	
	def show
	  @course_type = CourseType.find(params[:id])
	end
	
	def index
		@course_types = CourseType.all
	end
	
	def edit
		@course_type = CourseType.find(params[:id])
	end
	
	def update
		@course_type = CourseType.find(params[:id])
		
		if @course_type.update(course_type_params)
			redirect_to @course_type
		else
			render 'edit'
		end
	end
	
	def destroy
		@course_type = CourseType.find(params[:id])
		@course_type.destroy
		
		redirect_to course_types_path
	end
	
	private
		def course_type_params
			params.require(:course_type).permit(:name, :default_web_description, :default_email_description)
		end
end

app/helpers/course_types_helper.rb
module CourseTypesHelper
end

app/views/course_types/_course_type.html.erb
<tr>
	<td><%= course_type.name %></td>
	<td><%= course_type.default_web_description %></td>
	<td><%= course_type.default_email_description %></td>
	<td><%= link_to 'Show', course_type %></td>
	<td><%= link_to 'Edit', edit_course_type_path(course_type) %></td>
	<td><%= link_to 'Delete', course_type_path(course_type), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/course_types/_form.html.erb
<%= form_for @course_type do |f| %>

	<% if @course_type.errors.any? %>
	  <div id="errorExplanation">
		<h2><%= pluralize(@course_type.errors.count, "error") %> prohibited
		  this course type from being saved:</h2>
		<ul>
		<% @course_type.errors.full_messages.each do |msg| %>
		  <li><%= msg %></li>
		<% end %>
		</ul>
	  </div>
  <% end %>
  
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	
	<p>
		<%= f.label :default_web_description %><br>
		<%= f.text_area :default_web_description %>
	</p>
	
	<p>
		<%= f.label :default_email_description %><br>
		<%= f.text_area :default_email_description %>
	</p>
	
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/course_types/edit.html.erb
<h1>Edit Course Type</h1>

<%= render 'form' %>

<%= link_to 'Back', course_types_path %>

app/views/course_types/index.html.erb
<h1>Listing course types</h1>

<%= link_to 'New course type', new_course_type_path %>


  <tr>
    <th>Name</th>
    <th>Default Web Description</th>
	<th>Default Email Description</th>
	<th>Show</th>
	<th>Edit</th>
	<th>Delete</th>
  </tr>

  <%= render partial: "course_type", collection: @course_types %>

app/views/course_types/new.html.erb
<h1>New Course Type</h1>

<%= render 'form' %>

<%= link_to 'Back', course_types_path %>

app/views/course_types/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @course_type.name %>
</p>
 
<p>
  <strong>Web Description:</strong>
  <%= @course_type.default_web_description %>
</p>

<p>
  <strong>Email Description:</strong>
  <%= @course_type.default_email_description %>
</p>

<%= link_to 'Back', course_types_path %> &nbsp; | &nbsp;
<%= link_to 'Edit', edit_course_type_path(@course_type) %>