config/routes.rb
Cprsite::Application.routes.draw do
  resources :privilege_levels

  
  resources :course_types, :user_sessions, :courses, :organizations, :privilege_levels
  
  resources :users do
	member do
		get 'privilege_levels'
		patch 'update_user_privilege_levels'
	end
  end
  resources :account, :controller => "users"
    
  get "welcome/handsonly"
  get "welcome/learn"
  get "welcome/aed"
  get "welcome/info"
  get "welcome/index"

  root to: 'welcome#index'

 end

app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :courses
	has_and_belongs_to_many :privilege_levels

	acts_as_authentic do |c|
		c.login_field = :email
	end
	
	before_save do
		self.phone = self.phone.gsub(/\D/, "")
	end

	attr_accessor :password
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email_confirmation, presence: true, unless: :email_not_changed?
	validates :email, uniqueness: true, confirmation: {unless: :email_not_changed?}, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, message: "Not a valid email address"}
	validates :password, presence: true, length: {minimum: 6, maximum: 25}, confirmation: true, unless: :password_not_changed?
	validates :password_confirmation, presence: true, unless: :password_not_changed?
	validates :phone, presence: true
	validates :address_1, presence: true
	validates :city, presence: true
	
	def update_privilege_levels(privilege_level_ids)
		self.privilege_level_ids = privilege_level_ids
		return self.save(validate: false)
	end
	
	def email_not_changed?
		return email == self.email
	end
	
	def password_not_changed?
		return (!password || (password == self.password))
	end
	
	
	def to_s
		return self.last_name + ", " + self.first_name
	end
	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		
		if @user.save
			redirect_to @user
		else
			render 'new'
		end
	end
	
	def index
		@users = User.all
	end
	
	def show
		@user = User.find(params[:id])
	end
	
	def edit
		@user = User.find(params[:id])
	end
	
	def update
		@user = User.find(params[:id])
		
		if @user.update(user_params)
			flash[:notice] = "Account updated!"
			redirect_to @user
		else
			render 'edit'
		end
	end
	
	def destroy
		@user = User.find(params[:id])
		@user.destroy
		
		redirect_to users_path
	end
	
	private
		def user_params
			params.require(:user).permit(:first_name, :last_name, :email, :email_confirmation, :password, :password_confirmation, :phone, :address_1, :address_2, :city, :state, :zip, :country)
		end

end

app/views/users/_user.html.erb
<tr>
	<td><%= user.last_name %></td>
	<td><%= user.first_name %></td>
	<td><%= mail_to(user.email) %></td>
	<td><%= link_to 'Show', user %></td>
	<td><%= link_to 'Edit', edit_user_path(user) %></td>
	<td><%= link_to 'Edit Privileges', privilege_levels_user_path(user) %></td>
	<td><%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/users/index.html.erb
<h1>List all users</h1>

<%= link_to 'New user', new_user_path %>

<tr>
	<th>Last Name</th>
	<th>First Name</th>
	<th>Email</th>
	<th>Show</th>
	<th>Edit</th>
	<th>Privilege Levels</th>
	<th>Delete</th>
</tr>

<%= render @users %>

app/views/users/privilege_levels.html.erb
<%= form_for(@user, :url=> update_user_privilege_levels_user_path) do |f| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
			  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user's privilege levels from being saved:</h2>

			  <ul>
			  <% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			  <% end %>
			  </ul>
		</div>
	<% end %>
  
	<p>
		<%= f.label :privilege_levels %><br>
		<%= f.collection_select(:privilege_level_ids, PrivilegeLevel.all, :id, :to_s, {}, {:multiple=> true}) %>
	</p>
	
	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.first_name + " " + @user.last_name %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= mail_to(@user.email) %>
</p>

<p>
  <strong>Phone:</strong>
  <%= number_to_phone(@user.phone) %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address_1 %><br />
  <%= @user.address_2 %><br />
  <%= @user.city + ", " + @user.state + " " + @user.zip + " " + @user.country %>
</p>

<p>
	<strong>Privilege Levels:</strong>
	<%= @user.privilege_levels.join("; ") %>
</p>

<%= link_to 'Back', users_path %> &nbsp; | &nbsp;
<%= link_to 'Edit', edit_user_path(@user) %>