config/routes.rb
Cprsite::Application.routes.draw do
  resources :privilege_levels

  
  resources :course_types, :user_sessions, :courses, :organizations, :privilege_levels
  
  resources :users do
	member do
		get 'privilege_levels'
		patch 'update_user_privilege_levels'
	end
  end
  resources :account, :controller => "users"
    
  get "welcome/handsonly"
  get "welcome/learn"
  get "welcome/aed"
  get "welcome/info"
  get "welcome/index"

  root to: 'welcome#index'

 end

app/models/privilege_level.rb
class PrivilegeLevel < ActiveRecord::Base
	has_and_belongs_to_many :users
	
	def to_s 
		return self.name
	end
end

app/controllers/privilege_levels_controller.rb
class PrivilegeLevelsController < ApplicationController
  before_action :set_privilege_level, only: [:show, :edit, :update, :destroy]

  # GET /privilege_levels
  # GET /privilege_levels.json
  def index
    @privilege_levels = PrivilegeLevel.all
  end

  # GET /privilege_levels/1
  # GET /privilege_levels/1.json
  def show
  end

  # GET /privilege_levels/new
  def new
    @privilege_level = PrivilegeLevel.new
  end

  # GET /privilege_levels/1/edit
  def edit
  end

  # POST /privilege_levels
  # POST /privilege_levels.json
  def create
    @privilege_level = PrivilegeLevel.new(privilege_level_params)

    respond_to do |format|
      if @privilege_level.save
        format.html { redirect_to @privilege_level, notice: 'Privilege level was successfully created.' }
        format.json { render action: 'show', status: :created, location: @privilege_level }
      else
        format.html { render action: 'new' }
        format.json { render json: @privilege_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /privilege_levels/1
  # PATCH/PUT /privilege_levels/1.json
  def update
    respond_to do |format|
      if @privilege_level.update(privilege_level_params)
        format.html { redirect_to @privilege_level, notice: 'Privilege level was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @privilege_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /privilege_levels/1
  # DELETE /privilege_levels/1.json
  def destroy
    @privilege_level.destroy
    respond_to do |format|
      format.html { redirect_to privilege_levels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_privilege_level
      @privilege_level = PrivilegeLevel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def privilege_level_params
      params.require(:privilege_level).permit(:name)
    end
end

app/helpers/privilege_levels_helper.rb
module PrivilegeLevelsHelper
end

app/views/privilege_levels/_form.html.erb
<%= form_for(@privilege_level) do |f| %>
  <% if @privilege_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@privilege_level.errors.count, "error") %> prohibited this privilege_level from being saved:</h2>

      <ul>
      <% @privilege_level.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/privilege_levels/edit.html.erb
<h1>Editing privilege_level</h1>

<%= render 'form' %>

<%= link_to 'Show', @privilege_level %> |
<%= link_to 'Back', privilege_levels_path %>

app/views/privilege_levels/index.html.erb
<h1>Listing privilege_levels</h1>

  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

    <% @privilege_levels.each do |privilege_level| %>
      <tr>
        <td><%= privilege_level.name %></td>
        <td><%= link_to 'Show', privilege_level %></td>
        <td><%= link_to 'Edit', edit_privilege_level_path(privilege_level) %></td>
        <td><%= link_to 'Destroy', privilege_level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>


<br>

<%= link_to 'New Privilege level', new_privilege_level_path %>

app/views/privilege_levels/new.html.erb
<h1>New privilege_level</h1>

<%= render 'form' %>

<%= link_to 'Back', privilege_levels_path %>

app/views/privilege_levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @privilege_level.name %>
</p>

<%= link_to 'Edit', edit_privilege_level_path(@privilege_level) %> |
<%= link_to 'Back', privilege_levels_path %>