config/routes.rb
Cprsite::Application.routes.draw do
  resources :privilege_levels

  
  resources :course_types, :user_sessions, :courses, :organizations, :privilege_levels
  
  resources :users do
	member do
		get 'privilege_levels'
		patch 'update_user_privilege_levels'
	end
  end
  resources :account, :controller => "users"
    
  get "welcome/handsonly"
  get "welcome/learn"
  get "welcome/aed"
  get "welcome/info"
  get "welcome/index"

  root to: 'welcome#index'

 end

app/models/course.rb
class Course < ActiveRecord::Base
	belongs_to :organization
	has_and_belongs_to_many :instructors, class_name: "User"
	#has_and_belongs_to_many :attendees, class_name: "User"
	
	validates :name, presence: true
	validates :start, presence: true
	validates :end, presence: true
	validates :class_location, presence: true
	validates :organization_id, presence: true
	validates :max_capacity, presence: true, numericality: {only_integer: true, greater_than: 0}
	
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def new
		@course = Course.new
		
		@instructors = PrivilegeLevel.where(:name => "Instructor").joins(:users)[0].users
	end
	
	def create
		@course = Course.new(course_params)
		
		if @course.save
			redirect_to @course
		else
			render 'new'
		end
	end
	
	def show
	  @course = Course.find(params[:id])
	end
	
	def index
		@courses = Course.all
	end
	
	def edit
		@course = Course.find(params[:id])
		@instructors = PrivilegeLevel.where(:name => "Instructor").joins(:users)[0].users
	end
	
	def update
		@course = Course.find(params[:id])
		
		if @course.update(course_params)
			redirect_to @course
		else
			render 'edit'
		end
	end
	
	def destroy
		@course = Course.find(params[:id])
		@course.destroy
		
		redirect_to courses_path
	end
	
	private
		def course_params
			params.require(:course).permit(:name, :start, :end, :max_capacity, :web_description, :email_description, :class_location, :organization_id, :instructor_ids=>[])
		end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<tr>
	<td><%= course.name %></td>
	<td><%= course.class_location %></td>
	<td><%= course.start %></td>
	<td><%= course.end %></td>
	<td><%= link_to 'Edit', edit_course_path(course) %></td>
	<td><%= link_to 'Delete', course_path(course), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>

	<% if @course.errors.any? %>
	  <div id="errorExplanation">
		<h2><%= pluralize(@course.errors.count, "error") %> prohibited
		  this course from being created:</h2>
		<ul>
		<% @course.errors.full_messages.each do |msg| %>
		  <li><%= msg %></li>
		<% end %>
		</ul>
	  </div>
  <% end %>
  
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	
	<p>
		<%= f.label :start %> <br>
		<%= f.datetime_select :start %>
	</p>
	
	<p>
		<%= f.label :end %> <br>
		<%= f.datetime_select :end %>
	</p>
	
	<p>
		<%= f.label :class_location %><br>
		<%= f.text_field :class_location %>
	</p>
	
	<p>
		<%= f.label :max_capacity %><br>
		<%= f.text_field :max_capacity %>
	</p>
	
	<p>
		<%= f.label :organization_id %><br>
		<%= f.collection_select(:organization_id, Organization.all, :id, :name) %>
	</p>
	
	<p>
		<%= f.label :instructors %><br>
		<%= f.collection_select(:instructor_ids, @instructors, :id, :to_s, {}, {:multiple=> true}) %>
	</p>
	
	<p>
		<%= f.label :web_description %><br>
		<%= f.text_area :web_description %>
	</p>
	
	<p>
		<%= f.label :email_description %><br>
		<%= f.text_area :email_description %>
	</p>
	
	<p>
		<%= f.submit %>
	</p>
	
<% end %>

app/views/courses/_user.html.erb
<%= user.to_s %>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/courses/index.html.erb
<h1>List all courses</h1>

<%= link_to 'New course', new_course_path %>

<tr>
	<th>Name</th>
	<th>Location</th>
	<th>Start Time</th>
	<th>End Time</th>
	<th>Edit</th>
	<th>Delete</th>
</tr>

<%= render @courses %>

app/views/courses/new.html.erb
<tr><td align="center"><h1>New Course</h1></tr></td>

<tr><td align="center"><%= render 'form' %></tr></td>

<%= link_to 'Back', :back %>

app/views/courses/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
	<strong>Organization:</strong>
	<%= @course.organization %>
</p>

<p>
	<strong>Location:</strong>
	<%= @course.class_location %>
</p>

<p>
	<strong>Maximum Capacity:</strong>
	<%= @course.max_capacity %>
</p>

<p>
	<strong>Start:</strong>
	<%= @course.start.to_formatted_s(:db) %>
</p>

<p>
	<strong>End:</strong>
	<%= @course.end.to_formatted_s(:db) %>
</p>

<p>
	<strong>Instructors:</strong>
	<%= @course.instructors.join("; ") %>
</p>
	
<p>
	<strong>Web Description:</strong>
	<%= @course.web_description %>
</p>

<p>
	<strong>Email Description:</strong>
	<%= @course.email_description %>
</p>

<%= link_to 'Back', :back %> &nbsp; | &nbsp;
<%= link_to 'Edit', edit_course_path(@course) %>